services:  
  ros-master:
    image: ros:noetic
    ports:
      - "11311:11311"
    profiles:
      - core
    build:
      context: .
      dockerfile: ros_master_docker/Dockerfile
    container_name: ros-master
    command: roscore
    networks: [ rosnet ]
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=ros-master

  coordinator:
    build:
      context: .
      dockerfile: coordinator_docker/Dockerfile
    container_name: coordinator
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
    profiles:
      - core


  tasknode:
    build:
      context: .
      dockerfile: task_docker/Dockerfile
    container_name: tasknode
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
    profiles:
      - core


  robot1:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot1


    profiles:
      - robots
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot1
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=3.0
      - BATTERY=99.4

      

  robot2:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot2


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot2
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=3.0
      - BATTERY=20.5
    profiles:
      - robots
      

  robot3:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot3

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot3
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=-7.0
      - BATTERY=76.7
    profiles:
      - robots
      

  robot4:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot4


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot4
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=1.8
      - ROBOT_Y=8.0
      - BATTERY=75.3
    profiles:
      - robots
      

  robot5:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot5

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot5
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=2.0
      - BATTERY=65.0
    profiles:
      - robots
      

  robot6:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot6


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot6
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=5.0
      - BATTERY=84.9
    profiles:
      - robots
      

  robot7:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot7


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot7
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=5.5
      - ROBOT_Y=-4.0
      - BATTERY=61.9
    profiles:
      - robots
      

  robot8:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot8


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot8
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=4.0
      - BATTERY=74.1
    profiles:
      - robots
      

  robot9:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot9


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot9
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=-8.0
      - BATTERY=54.9
    profiles:
      - robots
      

  robot10:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot10

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot10
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-5.0
      - BATTERY=64.1
    profiles:
      - robots
      

  robot11:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot11


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot11
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=8.0
      - BATTERY=48.6
    profiles:
      - robots
      

  robot12:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot12

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot12
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-2.0
      - BATTERY=29.4
    profiles:
      - robots
      

  robot13:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot13

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot13
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=8.0
      - BATTERY=87.9
    profiles:
      - robots
      

  robot14:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot14

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot14
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-4.0
      - BATTERY=82.3
    profiles:
      - robots
      

  robot15:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot15


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot15
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=2.5
      - BATTERY=34.3
    profiles:
      - robots
      

  robot16:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot16

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot16
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=-10.0
      - BATTERY=53.9
    profiles:
      - robots
      

  robot17:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot17

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot17
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=9.0
      - BATTERY=49.2
    profiles:
      - robots
      

  robot18:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot18

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot18
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=5.0
      - BATTERY=42.3
    profiles:
      - robots
      

  robot19:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot19


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot19
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=1.8
      - ROBOT_Y=7.0
      - BATTERY=23.5
    profiles:
      - robots
      

  robot20:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot20

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot20
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=-2.5
      - BATTERY=46.8
    profiles:
      - robots
      

  robot21:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot21

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot21
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=6.0
      - BATTERY=81.6
    profiles:
      - robots
      

  robot22:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot22


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot22
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=-7.8
      - BATTERY=72.7
    profiles:
      - robots
      

  robot23:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot23

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot23
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=5.5
      - ROBOT_Y=-7.8
      - BATTERY=27.8
    profiles:
      - robots
      

  robot24:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot24

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot24
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=5.5
      - ROBOT_Y=2.5
      - BATTERY=36.5
    profiles:
      - robots
      

  robot25:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot25


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot25
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=0.0
      - BATTERY=79.2
    profiles:
      - robots
      

  robot26:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot26


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot26
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=6.0
      - BATTERY=45.0
    profiles:
      - robots
      

  robot27:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot27


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot27
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=3.0
      - BATTERY=74.8
    profiles:
      - robots
      

  robot28:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot28

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot28
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=7.0
      - BATTERY=26.9
    profiles:
      - robots
      

  robot29:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot29

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot29
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-1.0
      - BATTERY=71.4
    profiles:
      - robots
      

  robot30:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot30

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot30
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-0.5
      - ROBOT_Y=1.8
      - BATTERY=89.3
    profiles:
      - robots
      

  robot31:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot31


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot31
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=6.0
      - BATTERY=86.1
    profiles:
      - robots
      

  robot32:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot32


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot32
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=1.5
      - BATTERY=84.1
    profiles:
      - robots
      

  robot33:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot33


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot33
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=7.0
      - BATTERY=65.6
    profiles:
      - robots
      

  robot34:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot34


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot34
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-3.0
      - BATTERY=67.7
    profiles:
      - robots
      

  robot35:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot35


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot35
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=5.5
      - ROBOT_Y=-10.0
      - BATTERY=96.0
    profiles:
      - robots
      

  robot36:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot36
    profiles:
      - robots

    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot36
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-8.0
      - BATTERY=99.3



  robot37:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot37


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot37
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=4.0
      - BATTERY=30.0
    profiles:
      - robots


  robot38:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot38


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot38
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=1.8
      - ROBOT_Y=6.0
      - BATTERY=71.5
    profiles:
      - robots

  robot39:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot39


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot39
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-7.0
      - BATTERY=65.9
    profiles:
      - robots
      

  robot40:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot40


    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot40
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-3.0
      - ROBOT_Y=2.0
      - BATTERY=79.3
    profiles:
      - robots
      


networks:
  rosnet:
    driver: bridge
