services:  
  ros-master:
    build:
      context: .
      dockerfile: ros_master_docker/Dockerfile
    container_name: ros-master
    command: roscore
    networks: [ rosnet ]
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
      - ROS_HOSTNAME=ros-master

  coordinator:
    build:
      context: .
      dockerfile: coordinator_docker/Dockerfile
    container_name: coordinator
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data


  tasknode:
    build:
      context: .
      dockerfile: task_docker/Dockerfile
    container_name: tasknode
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311

  


  robot1:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot1
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot1
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=-4.0
      - BATTERY=32.9
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
  robot2:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot2
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot2
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=1.5
      - BATTERY=45.1
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot3:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot3
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot3
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=5.5
      - ROBOT_Y=-10
      - BATTERY=27.7
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
  robot4:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot4
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot4
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=3.5
      - ROBOT_Y=-5.6
      - BATTERY=63.3
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot5:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot5
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot5
      - PYTHONUNBUFFERED=1
      - ROS_MASTER_URI=http://ros-master:11311
      - ROBOT_X=-4.5
      - ROBOT_Y=2
      - BATTERY=20.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
  
  robot6:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot6
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot6
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-4.5
      - ROBOT_Y=-7
      - BATTERY=43.7
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot7:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot7
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot7
      - PYTHONUNBUFFERED=1
      - ROBOT_X=5.5
      - ROBOT_Y=-5.6
      - BATTERY=40.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot8:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot8
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot8
      - PYTHONUNBUFFERED=1
      - ROBOT_X=3.5
      - ROBOT_Y=-10
      - BATTERY=40.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot9:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot9
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot9
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-4.5
      - ROBOT_Y=1
      - BATTERY=40.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot10:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot10
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot10
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-3
      - ROBOT_Y=9
      - BATTERY=40.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot11:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot11
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot11
      - PYTHONUNBUFFERED=1
      - ROBOT_X=5.5
      - ROBOT_Y=-7.8
      - BATTERY=56.9
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot12:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot12
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot12
      - PYTHONUNBUFFERED=1
      - ROBOT_X=3.5
      - ROBOT_Y=-2.5
      - BATTERY=42.0
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot13:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot13
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot13
      - PYTHONUNBUFFERED=1
      - ROBOT_X=5.5
      - ROBOT_Y=1.5
      - BATTERY=23.7
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data


  robot14:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot14
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot14
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-0.5
      - ROBOT_Y=5
      - BATTERY=53.4
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot15:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot15
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot15
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-0.5
      - ROBOT_Y=3
      - BATTERY=47.3
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data


  robot16:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot16
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot16
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-0.5
      - ROBOT_Y=1.8
      - BATTERY=29.2
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data
  robot17:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot17
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot17
      - PYTHONUNBUFFERED=1
      - ROBOT_X=1.8
      - ROBOT_Y=6
      - BATTERY=25.2
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot18:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot18
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot18
      - PYTHONUNBUFFERED=1
      - ROBOT_X=-0.5
      - ROBOT_Y=6
      - BATTERY=25.2
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot19:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot19
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot19
      - PYTHONUNBUFFERED=1
      - ROBOT_X=3.5
      - ROBOT_Y=2.5
      - BATTERY=25.2
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data

  robot20:
    build:
      context: .
      dockerfile: robot_docker/Dockerfile
    container_name: robot20
    depends_on:
      - ros-master
    networks: [ rosnet ]
    environment:
      - ROBOT_NAME=robot20
      - PYTHONUNBUFFERED=1
      - ROBOT_X=5.5
      - ROBOT_Y=-5.6
      - BATTERY=25.2
    volumes:
      - ~/Desktop/coordinator_data:/root/catkin_ws/data



networks:
  rosnet:
    driver: bridge
